# Development profile
# MySQL Local
spring.datasource.url=jdbc:mysql://localhost:3306/the_garage?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=MySQL/2125

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Opcional: mostrar SQL formateado
spring.jpa.properties.hibernate.format_sql=true

# Puerto aplicacion
server.port=8080

#credenciales
garage.admin.username=admin
garage.admin.email=admin@thegarage.dev
garage.admin.password=Admin123!


garage.notifications.provider=smtp
garage.notifications.from-address=no-reply@thegarage.dev

# Mailtrap Email Testing SMTP
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=d2eef84a601016
spring.mail.password=9f4d09a70d203d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
